CLASS lsc_Z_I_Travel_M_MO DEFINITION INHERITING FROM cl_abap_behavior_saver.
  PROTECTED SECTION.

    METHODS save_modified REDEFINITION.

ENDCLASS.

CLASS lsc_Z_I_Travel_M_MO IMPLEMENTATION.

  METHOD save_modified.
  ENDMETHOD.

ENDCLASS.
